name: Run Ero
concurrency: decompile

on:
  repository_dispatch:
    types: [ start ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Update Worker State
      uses: webiny/action-post-run@2.0.1
      with:
        run: 'curl -H "Content-Type: application/json" -d "{"state"&#58; "${{ job.status }}", "version"&#58; "${{ github.event.client_payload.version }}", "commit"&#58; "${{ steps.commit.outputs.commit_hash }}"}" $${{ secrets.WORKER }}/complete'
    - name: Checkout Decompiler
      uses: actions/checkout@v3
      with:
        repository: 'jaacksondev/ero-decompiler'
        token: ${{ secrets.API_TOKEN_GITHUB }}
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ github.event.client_payload.java }}
    - name: Make Gradle Wrapper Executable
      run: chmod +x ./gradlew
    - name: Download Binaries
      env:
        CLIENT: ${{ github.event.client_payload.downloads.client.url }}
        CLIENT_MAPPINGS: ${{ github.event.client_payload.downloads.client_mappings.url }}
        SERVER: ${{ github.event.client_payload.downloads.server.url }}
        SERVER_MAPPINGS: ${{ github.event.client_payload.downloads.server_mappings.url }}
      run: wget -P run/ $CLIENT $CLIENT_MAPPINGS $SERVER $SERVER_MAPPINGS
    - name: Download Libraries
      env:
        LIBRARY_URLS: ${{ github.event.client_payload.libraries.urls }}
      run: wget -P run/libraries/ $LIBRARY_URLS
    - name: Cache Gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Decompile Minecraft
      run: ./gradlew run
    - name: Checkout Actions
      uses: actions/checkout@v3
      with:
        path: action
    - name: Commit Changes
      id: commit
      uses: ./action
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'run/output/.'
        destination_repo: 'jaacksondev/ero-minecraft-source'
        user_email: 'ero-git@pm.me'
        user_name: 'ero-git'
        commit_message: ${{ github.event.client_payload.version }}
